### ISSUE TITLE
Benchmark DBT model performance with expected MoH KE traffic

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-sync#108]
We have a model system that works and seems to hold up well. The purpose of this ticket is to benchmark with expected eCHIS traffic to make sure that the DBT runs stay up to date and are not constantly catching up to new data that is added.

**Comment by njuguna-n** [comment]
Summary of findings so far:

All tests were conducted on an EKS instance with the Postgres pod having 6GB in memory and 6 vCPUs resource limits. The DBT pod has 4GB of memory and 4 vCPUs. 

With around 44 million docs already synced I started adding additional docs at a rate of about 10 docs per minute. At this rate `dbt run` was taking roughly 14 minutes which is similar to a run with no additional docs being processed. The timer interval was initially 10 minutes but I slowly brought it down to 3 minutes with no discernible impact on the run time.

I then increased the sync rate to 5000 docs per minute, for context a rough [calculation](https://medic.slack.com/archives/C03SP4KRVEX/p1716887848719229?thread_ts=1716882700.341829&cid=C03SP4KRVEX) of expected MoH KE traffic is about 4883 docs per minute and let it run over the weekend. Unfortunately the DBT pod seems to have died and started afresh this morning so it's catching up with the docs and we don't have logs of the runs. **The current rate of docs sync is about 7000 docs per minute (so more than the expected MoH KE traffic) and the average run time of DBT (taken over the last 10 runs) is 25 minutes and 23 seconds. This is with a 3 minute delay between DBT runs. Please not that this with only 10 models with 3 of them being incremental tables and the rest being views.** 

@derickl @garethbowen how does the run time above look?

The next step is to flesh out the [base models](https://github.com/medic/cht-pipeline/issues/90) and rerun these tests.

**Comment by njuguna-n** [comment]
Last 10 DBT runs
```
08:12:29  Finished running 3 incremental models in 0 hours 23 minutes and 53.74 seconds (1433.74s).
08:40:06  Finished running 3 incremental models in 0 hours 24 minutes and 35.40 seconds (1475.40s).
09:06:45  Finished running 3 incremental models in 0 hours 23 minutes and 36.19 seconds (1416.19s).
09:33:28  Finished running 3 incremental models in 0 hours 23 minutes and 40.19 seconds (1420.19s).
10:03:32  Finished running 3 incremental models in 0 hours 27 minutes and 1.80 seconds (1621.80s).
10:31:13  Finished running 3 incremental models in 0 hours 24 minutes and 39.00 seconds (1479.00s).
10:57:56  Finished running 3 incremental models in 0 hours 23 minutes and 40.77 seconds (1420.77s).
11:26:16  Finished running 3 incremental models in 0 hours 25 minutes and 16.93 seconds (1516.93s).
11:56:19  Finished running 3 incremental models in 0 hours 27 minutes and 1.16 seconds (1621.16s).
12:27:59  Finished running 3 incremental models in 0 hours 28 minutes and 37.15 seconds (1717.15s).
```

Logstash throughput
```
"output_throughput" : {
    "current" : 246.7,
    "last_1_minute" : 232.9,
    "last_5_minutes" : 214.7,
    "last_15_minutes" : 288.1,
    "last_1_hour" : 259.3,
    "last_24_hours" : 78.72,
    "lifetime" : 119.7
  },
```

**Comment by Phil-Mwago** [comment]
@derickl any thoughts or concerns here?

**Comment by derickl** [comment]
Promising. Thanks for putting this together @njuguna-n 
I'm curious how these numbers translate in more real world scenarios where you have:
1) more models like 20x
2) nested models due to how inter-related they are
3) data updates or deletion (if you have nested materialized models)


This is the one mystery that is yet to be unravelled. cc @Phil-Mwago

**Comment by njuguna-n** [comment]
Seeing as the base benchmark with the existing models was done and a summary shared I will close this issue. To ensure additional benchmark tests are done with more real world models defined I have created a new [issue](https://github.com/medic/cht-pipeline/issues/96).
