### ISSUE TITLE
How we connect to MoH servers

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-sync#120]
To connect to CHT instances hosted by MoH Kenya we need to SSH into a proxy and then SSH into the desired instance including the staging server. The purpose of this ticket is to determine the best way to connect to the staging instance to be able to test the DBT models we will be creating.

**Comment by njuguna-n** [comment]
We can create an SSH tunnel and have cht-sync running locally and connected to couchdb via the tunnel. The main advantage of this is that it is realtively easy to set up the tunnel and start testing but the main drawback is that there might some data in the test instance that it private and should not be cloned to people's work stations.

The other option is to have cht-sync running in the staging instance itself and connected to a postgres instance either running in a Docker container or in an external service. We are still trying to [determine](https://medic.slack.com/archives/CHYAGKHN2/p1720424500028199) if there is already a staging postgres instance already deployed.

@alexosugo do you have any reservations about the data in the staging server being cloned on teammate's work stations?

**Comment by dianabarsan** [comment]
Can't we just connect to API instead?

**Comment by alexosugo** [comment]
@njuguna-n No reservations on the staging data. It's mostly testing data that doesn't belong to any actual users.

**Comment by derickl** [comment]
I believe there's a postgres server already set up in the staging instance

**Comment by njuguna-n** [comment]
@derickl would you happen to have the URL and credentials for that? Does it have enough resources for us to use it for cht-sync testing?

**Comment by njuguna-n** [comment]
We will be running cht-sync and cht-pipeline in EKS and use a postgres server hosted in EKS but is not internet facing. @witash already set up a connection to some prod instances as part of the effort to test some MoH KE [models](https://github.com/medic/cht-pipeline-moh-ke/issues/1). Closing this issue as there is nothing further to do and no additional info required.
