### ISSUE TITLE
Allow automatic model updates by adding dbt pacakge back to dataemon loop

### ISSUE THREAD

**Issue by witash** [medic/cht-sync#129]
previously, dataemon reinstalled on every loop.
This was removed because reinstalling packages and rebuilding models is an expensive operation and should only be run as a "deployment" step when models have changed.

The problem is, then you need something to trigger model deploymen and with the very simple dataemon script current, there's not any good options to do that; currently requires restarting the container which will not work in production;

So, tentatively add back dbt package to the main dataemon loop wo it will automatically update models when they are changed.

**Comment by andrablaj** [comment]
@witash I see the related PR #130 was merged. Can this issue be considered done, or is there any extra work needed?
