### ISSUE TITLE
Document a migration path from couch2pg to cht-sync and cht-pipeline

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-sync#136]
A large number (maybe all?) of existing CHT deployments already make use couch2pg to move their data to postgres for analytics and building dashboards and having them make use of cht-sync would be better and future proof. To make this migration easier we should have detailed instructions of the processes and steps involved and what should be considered to minimise project disruption.

**Comment by andrablaj** [comment]
also, related to https://github.com/medic/cht-docs/issues/1299.

**Comment by andrablaj** [comment]
[PR](https://github.com/medic/cht-docs/pull/1494#pullrequestreview-2256727656)

**Comment by njuguna-n** [comment]
[PR](https://github.com/medic/cht-docs/pull/1494) merged.
