### ISSUE TITLE
Collect aggregate data and submit back to a central repo

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-sync#14]
There are two main classes of data that we want to submit to a central repo...

1. Impact data. Knowing the impact the CHT is having helps focus our efforts on those that have the best impact. Additionally it can be used to justify grant applications to continue developing the CHT. Currently this is collected manually, is labor intensive, and prone to delays and bugs.
2. Usage data. Being able to query user telemetry across projects and understand _how_ the CHT is being used is critical for informing on potential improvements, and assessing the success of delivered improvements.

Data collection must be opt-in, and any data collected must be completely free of PII (aggregated and/or sanitized) so we don't risk exposing patient information.

**Comment by njuguna-n** [comment]
Hi @garethbowen is this something we still want to do?

**Comment by garethbowen** [comment]
We still want to collect the data but I suspect the solution will be different (ie: in cht-core). Closing as won't fix.
