### ISSUE TITLE
Deploy on Gamma

### ISSUE THREAD

**Issue by samuelimoisili** [medic/cht-sync#23]
This ticket aims to deploy CHT Sync using the existing DBT model on the Gamma environment. 

Description:

- Deploy CHT Sync on the Gamma environment.
- Utilize the current DBT model for data transformation.
- Ensure seamless integration and compatibility between CHT Sync and the DBT model.
- Perform necessary configuration and testing to ensure successful deployment.
- Document the deployment process and any relevant instructions or dependencies.

Help @medic/site-reliability-engineering

**Comment by andrablaj** [comment]
@samuelimoisili did you manage to get the support you needed from SRE? Otherwise, I suggest sharing this ticket in Slack or create a related ticket on the SRE board [here](https://github.com/medic/medic-infrastructure).
