### ISSUE TITLE
Create default Superset dashboard

### ISSUE THREAD

**Issue by samuelimoisili** [medic/cht-sync#24]
Create a default superset dashboard for the default data model.

__TODO__: Flesh out the scope of the dashboard.

**Comment by samuelimoisili** [comment]
I had a discussion with @njogz and he suggested we use default models to create superset dashboard.

**Comment by andrablaj** [comment]
Comment from @yrimal 
> In a default dashboard, can we add some basic calculation for reporting purpose? Please tag me in when we’re working on this, so that I can provide those metrics and logic.
