### ISSUE TITLE
Version CHT Sync

### ISSUE THREAD

**Issue by samuelimoisili** [medic/cht-sync#35]
Add versioning to the cht-sync repo and make use of the [Semantic Release](https://github.com/semantic-release/semantic-release) package to automate the release and versioning process. The setup should also include setting up [Conventional Changelog](https://github.com/conventional-changelog/commitlint#getting-started) for both local and CI environments to ensure commit messages are compliant.

**Comment by andrablaj** [comment]
Done via #144
