### ISSUE TITLE
Patch Logstash Docker Image to fix SSL issue

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-sync#43]
The current image we use to build the Logstash container uses acouchdb plugin that was last released in [2019](https://github.com/fielded/logstash-input-couchdb_changes/tags). There is a [bug](https://github.com/logstash-plugins/logstash-input-couchdb_changes/issues/43) where the secure option does not use https protocol. Additionally it seems that Let's Encrypt certs do not work possibly due to the dated code not have updated root ca certs. The proposed solution is to [patch](https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html#installing-local-plugins) the plugin while building the Docker container.

**Comment by mrjones-plip** [comment]
For some deployments you can still get CHT Sync to work if:
* you're running your CouchDB server on port 80 and it redirects to port 443
* port 443 is running HTTPS with not Let's Encrypt certs
