### ISSUE TITLE
Publish 2 reusable default schemas

### ISSUE THREAD

**Issue by Phil-Mwago** [medic/cht-sync#47]
These reusable schemas will be used to build activity dashboards.

**Comment by njuguna-n** [comment]
@Phil-Mwago is this related to #24?

**Comment by Phil-Mwago** [comment]
@njuguna-n these are not related. I think this has now changed to having reusable base models while the default dashboard (with activity widgets) was not feasible for general re-use as programatic requirements differ hence they'd have little impact. I will close #24

**Comment by andrablaj** [comment]
@Phil-Mwago can this issue be closed, as (reusable) base models were created and documented?

**Comment by andrablaj** [comment]
I will close this issue as `Deprioritized`. We can open a new one if this need is identified in the future.
