### ISSUE TITLE
BRAC - CHP Follow Up - Create instance to host BRAC cht-sync instance

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-sync#66]
The instance created here is no longer accessible so there is a need to create an instance where cht-sync will be hosted

**Comment by njuguna-n** [comment]
Instance created [here](https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#InstanceDetails:instanceId=i-04a3c5a581d79db5a).

**Comment by andrablaj** [comment]
@njuguna-n Closing this issue as marked as `Done`.
