### ISSUE TITLE
Document a recommended pattern of using cht-sync against multiple CouchDB instances

### ISSUE THREAD

**Issue by andrablaj** [medic/cht-sync#79]
Document a recommended pattern of using cht-sync against multiple CouchDB instances and linked to one PostgreSQL server.

As an example, there are MoHs hosted across several instances (mostly by county) and all data is synced to 1 PostgreSQL database.

This ticket can be moved to cht-docs if there are not required code changes. TBD. 

[Related Slack conversation](https://medic.slack.com/archives/C02N5UGRABF/p1711460396885439)

**Comment by witash** [comment]
multiple instances config is found in the deployment documentation
