### ISSUE TITLE
Increase cht-sync throughput

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-sync#80]
Cht-sync is currently running aginst the https://brac-clone-for-phil.dev.medicmobile.org instance but syncing of documents is currently very slow. When I checked a few hours ago it had a backlog of 41,168,339 documents to be synced (see screenshot below).

![Image](https://github.com/medic/cht-sync/assets/141340177/554653e3-29eb-446c-82cc-4394a46c6e7f)

**Comment by njuguna-n** [comment]
I looked into increasing PostgREST connections but after reading the [documentation](https://postgrest.org/en/v12/references/connection_pool.html) I decided against it and looked into logstash performance instead. [Pipeline stats](https://www.elastic.co/guide/en/logstash/current/node-stats-api.html#pipeline-stats) for the active logstash pipeline showed a flow rate of about 9 docs per second so looking into how to increase this. There are two main [levers](https://www.elastic.co/guide/en/logstash/current/tuning-logstash.html) to pull to increase performance i.e. worker count and batch size. I have tried adding an environment variable called `PIPELINE_WORKERS` and setting it to 100 then restarting the logstash container but that did not increase the actual worker count which remained at 4. I will continue with the performance tuning and investigations tomorrow.

CC: @lorerod in case you are able to look into this during your work day.

![Image](https://github.com/medic/cht-sync/assets/141340177/3798648a-a7d0-4f6b-83b6-f00a12dd6122)

**Comment by lorerod** [comment]
@njuguna-n do you have a PR for this? or a branch?

**Comment by njuguna-n** [comment]
@lorerod no specific branch or PR yet. I was playing around with existing config to see what works.

**Comment by njuguna-n** [comment]
Using redis has increased throughput to around 1000 docs per second with 250 logstash workers. I'll try adding more worker to see if that can be improved. Currently data is not being copied over to postgres due to an error in the worker I created. Debugging that currently.



![Image](https://github.com/medic/cht-sync/assets/141340177/31490fb0-4d07-4589-8c2e-74a7dcd27d3d)

![Image](https://github.com/medic/cht-sync/assets/141340177/97988645-d37a-4fdb-b06d-5eb8e71c9038)

**Comment by njuguna-n** [comment]
The issue was that redis and the worker were not on the same Docker network. Replication is now happening but the speed has gone down but is still ten times faster than before, see screenshot below. I'll leave this to run as is over the weekend and cleanup my draft PR if it holds up well.

![Image](https://github.com/medic/cht-sync/assets/141340177/c8568b27-9fbe-4d3c-b7d4-b43969bb9f17)

**Comment by njuguna-n** [comment]
There was an issue with logstash logs becoming too big and filling disk space on the server leading to failures. After fixing that and restarting we now get [errors](https://postgrest.org/en/v12/references/errors.html#http-status-codes) from postgres about insufficient resources. We'll have to sort that out before continuing with this test. The good news is that the redis solution seems to be working well and the throughput went up to around 250 docs per second which is good enough for now. We can try and test the upper limits of that later when doing load testing.

![image](https://github.com/medic/cht-sync/assets/141340177/aab5359d-c1e7-4430-a82c-04cf3aee352a)

**Comment by andrablaj** [comment]
In case the `Java Heap Space Error` persists, I found [this article](https://stackoverflow.com/questions/27156145/heap-space-error-while-executing-logstash-with-a-large-dictionary-translate-fil) with some possible solutions for configuring Logstash.

**Comment by njuguna-n** [comment]
Reducing the number of workers from 200 to 100 seems to have worked in keeping the logstash container stable. The current throughput rate is 438 docs per second and expecting all docs to be synced in about 20 hours if it remains stable 🤞 


![Image](https://github.com/medic/cht-sync/assets/141340177/f6c0b1d6-5a9f-4e3e-9755-4f2b1485148c)
