### ISSUE TITLE
 Document server requirements & needed setup to run CHT Sync successfully

### ISSUE THREAD

**Issue by andrablaj** [medic/cht-sync#85]
Document server requirements & needed setup to run CHT Sync successfully.

**Comment by andrablaj** [comment]
@njuguna-n @witash is there anything we need to document related to eventual server requirements for CHT Sync? (such as storage space, RAM, etc)

**Comment by njuguna-n** [comment]
@andrablaj I think it's a bit early to document anything. The MoH Kenya deployment will likely provide some useful information on server requirements for production so let's see that to conclusion first.

**Comment by njuguna-n** [comment]
Coming back to this: Given this [issue](https://github.com/medic/cht-sync/issues/145) where the Postgres container was running out of disk space I think we should provide some ball park resource requirements for Postgres especially disk size. This is of course very dependent on the documents and the dbt models defined for a deployment but having a rough estimate would still be helpful.

**Comment by njuguna-n** [comment]
[PR](https://github.com/medic/cht-docs/pull/1584) adding instructions for Postgres size estimation merged.
