### ISSUE TITLE
Objects getting dropped by CHTSync during refresh

### ISSUE THREAD

**Issue by billwambua** [medic/cht-sync#9]
When CHTSync is doing a refresh, it is dropping objects and recreating them. This causes issues because if the database is queried while a refresh is going on, the functions will not return any data.

Views
A full Brac dbt config has 42 views
![Selection_086](https://user-images.githubusercontent.com/17000106/187175956-51d767bb-789d-47a2-82b3-1602ca9efd7e.png)
Here is a screenshot in the midst of a CHTSync run showing only 18 views.
![Selection_084](https://user-images.githubusercontent.com/17000106/187176046-ace44f97-8108-46a6-b1eb-bdbb270df52f.png)

By `SELECT * FROM pg_catalog.pg_tables where schemaname= 'dbt_clone';`, it seems tables are not being dropped, but they are now taking very long to update.

cc @njogz @derickl

**Comment by derickl** [comment]
Seems related but unsure how to interpret the last comment in the thread https://discourse.getdbt.com/t/why-are-my-views-being-dropped-when-the-incremental-model-it-refs-is-being-updated/689/12

**Comment by andrablaj** [comment]
@witash is this error still happening? (this issue is very old). If not, can we close the ticket?

**Comment by njuguna-n** [comment]
@andrablaj this would still happen for tables being refreshed (similar [issue](https://github.com/moh-kenya/cht-pipeline-moh-ke/issues/135)) but there is a workaround using materialized views like we did to solve the linked issue. This is how dbt is designed to work so we can close this issue.
